Add Kitchen and Travis
salt-formulas/salt-formula-horizon pull request #3
Opened 2017-02-14 13:29 UTC by Martin819

2017-02-14 15:17 UTC, fpytloun commented on tests/pillar/cluster.sls
> +      encryption: encryption
This should be set to "ssl", not "encryption"

2017-02-15 09:33 UTC, Martin819 commented
"encryption: ssl" corrected on both pillars

2017-02-15 09:33 UTC, epcim commented
I enabled travis, wait to finish build.

2017-02-15 09:40 UTC, epcim requested changes
I would keep only single or cluster test. They don't differ much. Anyway we test only on single instance.

Cluster is worth to check iteration over dict entries. That will be anyway tested in upper stage.

2017-02-15 09:40 UTC, epcim commented on .gitignore
> +kitchen-init.sh
this file should never be there..

2017-02-15 09:40 UTC, epcim commented on .kitchen.yml
> +
whitespaces, fix (latest kitchen_init.sh on upstream is already fixed)

2017-02-15 09:40 UTC, epcim commented on .kitchen.yml
> +platforms:
add space

2017-02-15 09:40 UTC, epcim commented on .travis.yml
> +  - test ! -e .kitchen.yml || bundle exec kitchen test
I suggest to add gitter/slack notification settings to default travis. Especially disable failed builds to be notified globally/owners (ie: only to commit author)

2017-02-15 09:42 UTC, epcim commented
@fpytloun pls consider globally to update run_tests with: https://github.com/salt-formulas/salt-formula-opencontrail/pull/2/files#diff-6734f3f06fbfda089cd1d6eef82301caR47

2017-02-15 14:08 UTC, merged